#722: introduce `collapseCustomFragments` option
kangax/html-minifier pull request #723
Opened 2016-09-23 18:35 UTC by adamchal

…in order to collapse white space around `ignoreCustomFragments` (default: false).  This resolves issue #722.

Default behavior introduced from #436 is preserved.  Only setting `collapseCustomFragments` to `true` will collapse the white space.

_**Note:** I did not add the the compiled files in `dist/` in order to avoid merge conflict hell. Assumed you didn’t want that included in PRs._

2016-09-24 06:40 UTC, alexlamsl commented on README.md
> +| `collapseCustomFragments`      | Collapse white space around `ignoreCustomFragments`. | `false` |
Given that you are removing whitespaces surrounding the custom fragments indiscriminately, may I suggest calling this `trimCustomFragments`?

2016-09-24 06:45 UTC, alexlamsl commented on README.md
> +| `collapseCustomFragments`      | Collapse white space around `ignoreCustomFragments`. | `false` |
Given that you are removing whitespaces surrounding the custom fragments indiscriminately, may I suggest calling this `trimCustomFragments`?

2016-09-24 06:45 UTC, alexlamsl commented on tests/minifier.js
> +  }), output);
May I get a few more tests here with:
- whitespaces before and/or after `<? ... ?>`
- contents before and/or after `<? ... ?>`
- consecutive custom fragments

2016-09-24 06:46 UTC, alexlamsl requested changes
A couple of suggestions, otherwise LGTM.

2016-09-25 13:51 UTC, adamchal commented
Renamed ~~`collapseCustomFragments`~~ to `trimCustomFragments` and added more tests with suggested scenarios.

2016-09-25 14:18 UTC, alexlamsl approved these changes

2016-09-25 14:20 UTC, merged

2016-09-25 14:21 UTC, alexlamsl commented
@adamchal thanks a lot!

2016-09-25 21:25 UTC, adamchal commented
@alexlamsl no problem.  Thanks for maintaining this.