Remove change-case from dependencies
kangax/html-minifier pull request #736
Opened 2016-11-03 11:23 UTC by vlyahovich

Change-case lib is too distributed into packages that not needed and it has too much functionality twat we aren't using. Also we really need only one method in `cli.js` from it. So I suggest to remove this dependencies in favor of a simplified method.

2016-11-03 11:27 UTC, vlyahovich commented
Seems like `jslint` problems already in main branch

2016-11-06 09:23 UTC, alexlamsl commented
I don't see any reasons to remove that dependency which works as it is. I may be persuaded if we depend on the (two) individual sub-modules rather than `change-case` directly, but even then it's not exactly a big deal.

2016-11-06 09:25 UTC, alexlamsl requested changes

2016-11-06 09:25 UTC, alexlamsl commented on dist/htmlminifier.js
> + * @license amdefine 1.0.1 Copyright (c) 2011-2016, The Dojo Foundation All Rights Reserved.
Please don't commit files under `dist/` - they will be generated and updated when a release is made.

2016-11-07 14:39 UTC, vlyahovich commented
Yes, I agree that it is not a big deal. But having many unnecessary packages adds up to build time. I've done some changes, can you please look one more time? Thanks!

2016-11-08 06:50 UTC, alexlamsl requested changes
Looks okay with some final nits.

2016-11-08 06:50 UTC, alexlamsl commented on cli.js
> +var paramCase = require('param-case');
Please sort these `require()` in alphabetical order

2016-11-08 06:50 UTC, alexlamsl commented on package.json
> +    "param-case": "2.1.x",
Please sort these dependencies in alphabetical order

2016-11-08 07:06 UTC, vlyahovich commented
Done with review. Please take another look.

2016-11-08 08:38 UTC, alexlamsl approved these changes

2016-11-08 08:38 UTC, merged

2016-11-08 08:39 UTC, alexlamsl commented
Thanks for working on this.

2016-11-08 08:40 UTC, vlyahovich commented
Thanks! Appreciate your work.