Add ability to remove only empty `<script>` and `<style>` tags
kangax/html-minifier pull request #742
Opened 2016-11-10 10:18 UTC by sparanoid

I'd like the ability to remove empty `<script>` and `<style>` tags even when `removeEmptyElements` is disabled, these empty tags much safer than other empty elements.

2016-11-10 15:40 UTC, alexlamsl requested changes
I'd prefer extending `removeEmptyElements` then adding two new options.

Also some tests for the new functionality would be nice.

2019-09-30 00:34 UTC, anonyco commented
Wouldn't this remove `<script src="/path/to/file.js" async defer></script>` because it has no content (only an `src` attribute)?

2019-09-30 00:37 UTC, anonyco approved these changes

2019-09-30 00:37 UTC, anonyco commented on src/htmlminifier.js
> +        if (isElementEmpty && tag === 'script') {
I suggest changing this line to `        if (isElementEmpty && tag === 'script' && !attrs.src) {` so that external scripts do not get removed.

2023-08-28 07:13 UTC, closed without merging